config/routes.rb
Rails.application.routes.draw do

  root 'home#homepage'

  get '/homepage', :to=> 'home#homepage'
  get '/homepage/moveFirstFileGoogleToDropbox', :to => 'home#moveFirstFileGoogleToDropbox'
  get '/homepage/moveFirstFileDropboxToGoogle', :to => 'home#moveFirstFileDropboxToGoogle'
  get '/homepage/download', :to => 'home#download'
  post '/homepage/upload', :to => 'home#upload'

  get '/login', :to => 'logins#new'
  post '/login', :to => 'logins#create'
  get '/logout', :to => 'logins#destroy'
  get 'logins/destroy'
  get '/signup', :to => 'users#new'
  post '/signup', :to => 'users#create'

  get   '/sessions/login', :to => 'sessions#new'
  get '/auth/:provider/callback', :to => 'sessions#create'
  get '/auth/failure', :to => 'sessions#failure'

  get '/homepage/get_google_file_url', :to => 'home#get_google_file_url'
  get '/homepage/get_dropbox_file_url', :to => 'home#get_dropbox_file_url'
  get '/homepage/downloadSplit', :to => 'home#downloadSplit'
  get '/homepage/uploadToDropbox', :to => 'home#uploadToDropbox'
  get '/homepage/uploadToGoogle', :to => 'home#uploadToGoogle'
  get '/homepage/uploadSplit', :to => 'home#uploadSplit'
  get '/homepage/uploadMirror', :to => 'home#uploadMirror'
  get '/homepage/swapLeftPane', :to => 'home#swapLeftPane'
  get '/homepage/swapRightPane', :to => 'home#swapRightPane'

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def new

	end 

	def create
		user = User.find_by(email: params[:login][:email].downcase)
	    if user && user.authenticate(params[:login][:password])
	      log_in user
	      redirect_to controller: 'home', action: 'homepage'
	    else
	      flash.now[:danger] = 'Invalid email/password combination'
	      render 'new'
	    end
	end

	def destroy
		log_out
		redirect_to root_url
	end
end

app/helpers/logins_helper.rb
module LoginsHelper
	def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
	end

    def logged_in?
        !current_user.nil?
    end

    def log_out
	   session.delete(:user_id)
	   @current_user = nil
       reset_session
	end
end

app/views/logins/new.html.erb
<% provide(:title, 'Log in') %>

<center> 
	<%= image_tag 'UCloud-logo-TEMP!!!!.png', size: '160x100' %>

	<p style='font-size:28px'>One account. All of UCloud.</p>
	<p style='font-size:18px'>Sign in to continue to UCloud.</p>
	<br>
	<div class='container' style='width:300'>
		<div class='jumbotron'>
			<%= form_for :login, url: login_path do |f| %>
				<%= f.email_field :email, class: 'form-control', placeholder: 'Enter your email'%><br>
				<%= f.password_field :password, class: 'form-control', placeholder: 'Password'%><br>

				<%= f.submit 'Sign in', class: 'btn btn-primary form-control'%>
			<% end %>
		</div>
	</div>
	<%= link_to 'Create account', controller: 'users', action: 'new'%>

</center>